[tool]
[tool.proman]
authors = ["Jesse P. Johnson"]
name = "check"
description = "Description for the project"
version = "0.1.0"

[tool.proman.dependencies]
flask = "*"

[tool.proman.dev-dependencies]
